name: Build and Deploy (Dev)
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Rebuild Node Sass
        run: npm rebuild node-sass
      - name: Install Dependencies
        run: npm i
      - name: Remove build directory
        run: rm -rf build
      - name: Create build directory
        run: mkdir build
      - name: Build
        env:
          REACT_APP_API_KEY: ${{ secrets.DEV_REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.DEV_REACT_APP_AUTH_DOMAIN }}
          REACT_APP_DATABASE_URL: ${{ secrets.DEV_REACT_APP_DATABASE_URL }}
          REACT_APP_PROJECT_ID: ${{ secrets.DEV_REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.DEV_REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.DEV_REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.DEV_REACT_APP_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.DEV_REACT_APP_MEASUREMENT_ID }}
        run: CI= npm run build
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Archive
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: secret-toymaker-dev
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The project has been deployed to dev: https://secret-toymaker-dev.web.app"
