name: Build Dev
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Remove dist directory
        run: rm -rf dist-dev
      - name: Create dist directory
        run: mkdir dist-dev
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-dev
          path: dist-dev
